# Generated by Django 5.2.3 on 2025-08-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserLogin",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=30)),
                ("user_mnum", models.CharField(max_length=15)),
                ("user_uname", models.CharField(max_length=30)),
                ("user_psw", models.CharField(max_length=15)),
                ("user_pic", models.ImageField(upload_to="images/")),
                ("user_state", models.CharField(max_length=30)),
            ],
        ),
    ]
