# Generated by Django 5.2.3 on 2025-08-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("d_id", models.AutoField(primary_key=True, serialize=False)),
                ("d_name", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Requests",
            fields=[
                ("req_id", models.AutoField(primary_key=True, serialize=False)),
                ("req_brief", models.CharField(max_length=500)),
                ("req_wmnum", models.CharField(max_length=16)),
                ("req_loc", models.CharField(max_length=100)),
                ("req_time", models.TimeField(blank=True, default=None, null=True)),
                (
                    "req_img",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLogin",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=30)),
                ("user_mnum", models.CharField(max_length=15)),
                ("user_uname", models.CharField(max_length=30)),
                ("user_psw", models.CharField(max_length=15)),
                ("user_pic", models.ImageField(upload_to="images/")),
                ("user_state", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="AcceptedRequests",
            fields=[
                ("areq_id", models.AutoField(primary_key=True, serialize=False)),
                ("areq_status", models.CharField(default=None, max_length=25)),
                (
                    "areq_number",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loginDetail.requests",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechLogin",
            fields=[
                ("tech_id", models.AutoField(primary_key=True, serialize=False)),
                ("tech_name", models.CharField(max_length=40)),
                ("tech_email", models.CharField(max_length=50)),
                ("tech_mnum", models.CharField(max_length=15)),
                ("tech_exp", models.CharField(max_length=20)),
                ("tech_add", models.CharField(max_length=200)),
                ("tech_pic", models.ImageField(upload_to="images/")),
                ("tech_uravl", models.BooleanField(default=False)),
                ("tech_uname", models.CharField(max_length=30)),
                ("tech_psw", models.CharField(max_length=30)),
                (
                    "tech_dept",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loginDetail.departments",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="requests",
            name="req_dept",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loginDetail.techlogin",
            ),
        ),
        migrations.AddField(
            model_name="requests",
            name="req_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loginDetail.userlogin",
            ),
        ),
    ]
