# Generated by Django 5.2.3 on 2025-08-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginDetail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acceptedrequests",
            name="areq_status",
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
