# Generated by Django 5.2.3 on 2025-08-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginDetail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechLogin",
            fields=[
                ("tech_id", models.AutoField(primary_key=True, serialize=False)),
                ("tech_name", models.CharField(max_length=40)),
                ("tech_email", models.CharField(max_length=50)),
                ("tech_mnum", models.CharField(max_length=15)),
                ("tech_dept", models.CharField(max_length=40)),
                ("tech_exp", models.CharField(max_length=20)),
                ("tech_add", models.CharField(max_length=200)),
                ("tech_pic", models.ImageField(upload_to="images/")),
                ("tech_uravl", models.BooleanField(default=False)),
                ("tech_uname", models.CharField(max_length=30)),
                ("tech_psw", models.CharField(max_length=30)),
            ],
        ),
    ]
