# Generated by Django 5.2.3 on 2025-08-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginDetail", "0002_alter_acceptedrequests_areq_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acceptedrequests",
            old_name="areq_number",
            new_name="areq_unumber",
        ),
    ]
