# Generated by Django 5.2.3 on 2025-08-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginDetail", "0002_techlogin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requests",
            fields=[
                ("req_id", models.AutoField(primary_key=True, serialize=False)),
                ("req_brief", models.CharField(max_length=500)),
                ("req_wmnum", models.CharField(max_length=16)),
                ("req_loc", models.CharField(max_length=100)),
                ("req_time", models.TimeField(blank=True, default=None, null=True)),
                (
                    "req_img",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="images/"
                    ),
                ),
                (
                    "req_dept",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loginDetail.techlogin",
                    ),
                ),
                (
                    "req_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loginDetail.userlogin",
                    ),
                ),
            ],
        ),
    ]
