# Generated by Django 5.2.3 on 2025-08-12 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginDetail", "0003_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("d_id", models.AutoField(primary_key=True, serialize=False)),
                ("d_name", models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name="techlogin",
            name="tech_dept",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loginDetail.departments",
            ),
        ),
    ]
